# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a36fca73bd0af83a23be6899d2dd40b54c6352a394eabb0a0857580202a51fc018a0be9645c055e53dbb4a1643521b9674c0c616314fdb151356b84b2d37db7

test:
  secret_key_base: a172a7cc2a3640fe4818a0f0ee650e84283c1c8f5bbaa6406c1dd7df613d55be9f2decd0d67aff8dab247fb2016f6cc412119ee5d0cc5b7ebf7a4324ff82db0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
